"""SQLite storage. One shared DB file (data/erm.db).

Redmine data (fetch_cache), refresh status (fetch_status), and the PP
Report's state (pp_report_months, pp_report_overrides) are single shared
rows — everyone refreshes the same underlying data and sees the same PP
Report figures. Only `user_prefs` (My Team, Project Manager id) is
per-user; those are genuine personal display preferences, not data.
"""

import os
import sqlite3
from contextlib import contextmanager

DEFAULT_DB_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "erm.db")
# Override with ERM_DB_PATH for local development/testing so ad hoc runs
# never touch real user data in the default data/erm.db.
DB_PATH = os.environ.get("ERM_DB_PATH", DEFAULT_DB_PATH)


def _connect():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


@contextmanager
def get_db():
    conn = _connect()
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


def _column_exists(conn, table, column):
    return any(row["name"] == column for row in conn.execute(f"PRAGMA table_info({table})"))


def _table_exists(conn, table):
    return conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name=?", (table,)).fetchone() is not None


def _extract_and_drop_legacy_user_scoped_tables(conn):
    """One-off migration for DBs created before Redmine data + PP Report
    became shared across all users (each user previously had their own
    fetch_cache/fetch_status/pp_report_months/pp_report_overrides row).

    fetch_cache/fetch_status aren't worth preserving — trivially
    regenerated by the next "Refresh from Redmine". pp_report_months and
    pp_report_overrides ARE preserved (locked figures, saved drafts
    represent real work): for each month (and each project within a
    month, for overrides), whichever user's row has the latest
    updated_on is kept as the new single shared row — a reasonable "most
    recent wins" merge when more than one user had touched PP Report
    before this change. Returns the extracted rows so the caller can
    re-insert them once the new (non-user-scoped) tables exist below."""
    migrated = {"pp_report_months": [], "pp_report_overrides": []}

    if _table_exists(conn, "pp_report_months") and _column_exists(conn, "pp_report_months", "user_id"):
        rows = conn.execute(
            """
            SELECT month, daily_rate, locked, locked_snapshot_json, updated_on
            FROM pp_report_months AS m1
            WHERE updated_on = (SELECT MAX(updated_on) FROM pp_report_months AS m2 WHERE m2.month = m1.month)
            GROUP BY month
            """
        ).fetchall()
        migrated["pp_report_months"] = [dict(r) for r in rows]
        conn.execute("DROP TABLE pp_report_months")

    if _table_exists(conn, "pp_report_overrides") and _column_exists(conn, "pp_report_overrides", "user_id"):
        rows = conn.execute(
            """
            SELECT month, project_id, total_revenue, risk, notes, updated_on
            FROM pp_report_overrides AS o1
            WHERE updated_on = (
                SELECT MAX(updated_on) FROM pp_report_overrides AS o2
                WHERE o2.month = o1.month AND o2.project_id = o1.project_id
            )
            GROUP BY month, project_id
            """
        ).fetchall()
        migrated["pp_report_overrides"] = [dict(r) for r in rows]
        conn.execute("DROP TABLE pp_report_overrides")

    if _table_exists(conn, "fetch_cache") and _column_exists(conn, "fetch_cache", "user_id"):
        conn.execute("DROP TABLE fetch_cache")

    if _table_exists(conn, "fetch_status") and _column_exists(conn, "fetch_status", "user_id"):
        conn.execute("DROP TABLE fetch_status")

    return migrated


def _reinsert_migrated_data(conn, migrated):
    for row in migrated["pp_report_months"]:
        conn.execute(
            "INSERT INTO pp_report_months (month, daily_rate, locked, locked_snapshot_json, updated_on) VALUES (?, ?, ?, ?, ?)",
            (row["month"], row["daily_rate"], row["locked"], row["locked_snapshot_json"], row["updated_on"]),
        )
    for row in migrated["pp_report_overrides"]:
        conn.execute(
            "INSERT INTO pp_report_overrides (month, project_id, total_revenue, risk, notes, updated_on) VALUES (?, ?, ?, ?, ?, ?)",
            (row["month"], row["project_id"], row["total_revenue"], row["risk"], row["notes"], row["updated_on"]),
        )


def _migrate(conn):
    """One-off schema tweaks to a table that already existed before the
    tweak was introduced — CREATE TABLE IF NOT EXISTS alone can't add a
    column to a table that's already on disk from an earlier version."""
    if not _column_exists(conn, "users", "is_admin"):
        conn.execute("ALTER TABLE users ADD COLUMN is_admin INTEGER NOT NULL DEFAULT 0")
    if not _column_exists(conn, "pp_report_overrides", "risk"):
        conn.execute("ALTER TABLE pp_report_overrides ADD COLUMN risk REAL")
    if not _column_exists(conn, "pp_report_overrides", "completion_override"):
        # Hand-edited Project Completion (see pp_report.py's compute_row) —
        # NULL means "use the formula-derived value", same None-means-auto
        # convention as risk/total_revenue above.
        conn.execute("ALTER TABLE pp_report_overrides ADD COLUMN completion_override REAL")

    # Auto-refresh schedule (admin-configured, shared) — see app/scheduler.py.
    if not _column_exists(conn, "app_settings", "auto_refresh_mode"):
        conn.execute("ALTER TABLE app_settings ADD COLUMN auto_refresh_mode TEXT NOT NULL DEFAULT 'off'")
    if not _column_exists(conn, "app_settings", "auto_refresh_interval_minutes"):
        conn.execute("ALTER TABLE app_settings ADD COLUMN auto_refresh_interval_minutes INTEGER")
    if not _column_exists(conn, "app_settings", "auto_refresh_time"):
        conn.execute("ALTER TABLE app_settings ADD COLUMN auto_refresh_time TEXT")
    if not _column_exists(conn, "app_settings", "auto_refresh_weekday"):
        conn.execute("ALTER TABLE app_settings ADD COLUMN auto_refresh_weekday INTEGER")
    if not _column_exists(conn, "app_settings", "auto_refresh_day_of_month"):
        conn.execute("ALTER TABLE app_settings ADD COLUMN auto_refresh_day_of_month INTEGER")

    # When each kind of refresh last actually ran — shown on the
    # Dashboard/PP Report, separate from fetch_status's transient
    # in-progress state.
    if not _column_exists(conn, "fetch_status", "last_auto_fetch_on"):
        conn.execute("ALTER TABLE fetch_status ADD COLUMN last_auto_fetch_on TEXT")
    if not _column_exists(conn, "fetch_status", "last_manual_fetch_on"):
        conn.execute("ALTER TABLE fetch_status ADD COLUMN last_manual_fetch_on TEXT")

    # Who reopened a locked PP Report month, and when — surfaced as a
    # warning on the NEXT month's page (its Prev. Accumulated and other
    # previous-month-derived figures are provisional for as long as this
    # stays unlocked). Cleared again once the month is relocked.
    if not _column_exists(conn, "pp_report_months", "reopened_by"):
        conn.execute("ALTER TABLE pp_report_months ADD COLUMN reopened_by TEXT")
    if not _column_exists(conn, "pp_report_months", "reopened_on"):
        conn.execute("ALTER TABLE pp_report_months ADD COLUMN reopened_on TEXT")

    # KSA: last month's Amount to Take per project (feeds the PP Report's
    # "Earning last month" / trend arrow) — see pp_report.parse_ksa_workbook.
    if _table_exists(conn, "ksa_import") and not _column_exists(conn, "ksa_import", "previous_amount_to_take"):
        conn.execute("ALTER TABLE ksa_import ADD COLUMN previous_amount_to_take REAL")

    # Comma-separated Redmine project ids to leave out of the PP Report
    # entirely (admin-configured, shared) — see settings_store's
    # get/save_pp_report_excluded_project_ids.
    if not _column_exists(conn, "app_settings", "pp_report_excluded_project_ids"):
        conn.execute("ALTER TABLE app_settings ADD COLUMN pp_report_excluded_project_ids TEXT NOT NULL DEFAULT ''")

    # Comma-separated Redmine Project Manager ids whose projects are left
    # out of the PP Report entirely (admin-configured, shared) — same idea
    # as pp_report_excluded_project_ids above, but by manager instead of
    # by project id. See settings_store's get/save_pp_report_excluded_manager_ids.
    if not _column_exists(conn, "app_settings", "pp_report_excluded_manager_ids"):
        conn.execute("ALTER TABLE app_settings ADD COLUMN pp_report_excluded_manager_ids TEXT NOT NULL DEFAULT ''")


def _seed_default_countries(conn):
    """First-run only: seed the starting KSA/Kuwait/Lebanon/UAE rows with a
    zero rate so the Countries admin screen isn't empty. Only runs when the
    table is empty, so it never re-adds a country an admin deleted."""
    count = conn.execute("SELECT COUNT(*) AS c FROM countries").fetchone()["c"]
    if count > 0:
        return
    for name, currency in [("KSA", "SAR"), ("Kuwait", "KWD"), ("Lebanon", "USD"), ("UAE", "AED")]:
        conn.execute("INSERT INTO countries (name, daily_rate, currency) VALUES (?, 0, ?)", (name, currency))


def init_db():
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    with get_db() as conn:
        migrated = _extract_and_drop_legacy_user_scoped_tables(conn)

        conn.executescript(
            """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                is_admin INTEGER NOT NULL DEFAULT 0,
                created_on TEXT NOT NULL DEFAULT (datetime('now'))
            );

            -- Legacy per-user Redmine connection settings — no longer
            -- read by anything (superseded by app_settings below), kept
            -- only so upgrading doesn't drop old data outright.
            CREATE TABLE IF NOT EXISTS redmine_settings (
                user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
                redmine_url TEXT NOT NULL DEFAULT '',
                api_key_encrypted TEXT NOT NULL DEFAULT '',
                all_statuses_query_id TEXT NOT NULL DEFAULT '',
                updated_on TEXT NOT NULL DEFAULT (datetime('now'))
            );

            -- Cached last-fetch results, shared by every user — one row
            -- per kind. Refreshing is a single shared action; there's no
            -- per-user view of Redmine data anymore.
            CREATE TABLE IF NOT EXISTS fetch_cache (
                kind TEXT PRIMARY KEY,            -- 'projects' | 'timespent'
                data_json TEXT NOT NULL,
                fetched_on TEXT NOT NULL
            );

            -- Single shared refresh-in-progress state (id=1) — whichever
            -- user clicks "Refresh from Redmine", everyone sees the same
            -- in-flight status; started_by is just for transparency.
            CREATE TABLE IF NOT EXISTS fetch_status (
                id INTEGER PRIMARY KEY CHECK (id = 1),
                state TEXT NOT NULL DEFAULT 'idle',   -- idle | running | error | done
                message TEXT NOT NULL DEFAULT '',
                started_by TEXT NOT NULL DEFAULT '',
                updated_on TEXT NOT NULL DEFAULT (datetime('now'))
            );

            -- Monthly PP (Earned Revenue) report — one shared row per
            -- calendar month ('YYYY-MM'), not per user. daily_rate is the
            -- KW_Rate equivalent from the original workbook.
            -- locked_snapshot_json freezes the computed report (see
            -- app/pp_report.py) once a month is finalized, so re-fetching
            -- Redmine data later never silently changes a closed month,
            -- and so the NEXT month can carry forward each project's
            -- frozen "Accumulated" figure as its own "Previous
            -- Accumulated" input.
            CREATE TABLE IF NOT EXISTS pp_report_months (
                month TEXT PRIMARY KEY,
                daily_rate REAL NOT NULL DEFAULT 0,
                locked INTEGER NOT NULL DEFAULT 0,
                locked_snapshot_json TEXT,
                updated_on TEXT NOT NULL DEFAULT (datetime('now'))
            );

            -- The genuinely manual per-project inputs in the original
            -- workbook — Total Project Revenue (often hand-typed,
            -- sometimes a sum of several SAP orders), a local-only Risk
            -- override, and free-text Notes — shared across all users,
            -- same as everything else PP Report now uses.
            CREATE TABLE IF NOT EXISTS pp_report_overrides (
                month TEXT NOT NULL,
                project_id INTEGER NOT NULL,
                total_revenue REAL,
                risk REAL,
                notes TEXT NOT NULL DEFAULT '',
                updated_on TEXT NOT NULL DEFAULT (datetime('now')),
                PRIMARY KEY (month, project_id)
            );

            -- App-wide Redmine connection (single shared row, id=1).
            -- Admin-only to view/edit (see app/main.py).
            CREATE TABLE IF NOT EXISTS app_settings (
                id INTEGER PRIMARY KEY CHECK (id = 1),
                redmine_url TEXT NOT NULL DEFAULT '',
                api_key_encrypted TEXT NOT NULL DEFAULT '',
                all_statuses_query_id TEXT NOT NULL DEFAULT '',
                updated_on TEXT NOT NULL DEFAULT (datetime('now'))
            );

            -- The only per-user data left: My Team (comma-separated
            -- Redmine user ids, powers the Time Analysis "My Team" quick
            -- filter) and Project Manager id (this user's own Redmine
            -- user id as it appears in a project's "manager" field —
            -- defaults the Project Manager dropdown on the Dashboard and
            -- Time Analysis tab to "my projects").
            CREATE TABLE IF NOT EXISTS user_prefs (
                user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
                my_team_ids TEXT NOT NULL DEFAULT '',
                manager_id TEXT NOT NULL DEFAULT '',
                updated_on TEXT NOT NULL DEFAULT (datetime('now'))
            );

            -- Admin-configured Daily Rate per country. Countries are plain
            -- rows (not a fixed enum) so admins can add more later without
            -- a code change — see settings_store.seed_default_countries
            -- for the initial set.
            CREATE TABLE IF NOT EXISTS countries (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT UNIQUE NOT NULL,
                daily_rate REAL NOT NULL DEFAULT 0,
                currency TEXT NOT NULL DEFAULT '',
                updated_on TEXT NOT NULL DEFAULT (datetime('now'))
            );

            -- Per-consultant hourly rate (Redmine user id -> rate), keyed by
            -- the same user_id that appears on cached time entries. Not yet
            -- used by any report calculation — today's profitability
            -- formulas still use the per-country Daily Rate (see
            -- countries above) — this is scaffolding for a future switch
            -- to per-consultant costing. redmine_user_name is a cached
            -- display label only (refreshed whenever the admin screen is
            -- viewed), never used to identify the row.
            CREATE TABLE IF NOT EXISTS employees (
                redmine_user_id INTEGER PRIMARY KEY,
                redmine_user_name TEXT NOT NULL DEFAULT '',
                hourly_rate REAL NOT NULL DEFAULT 0,
                updated_on TEXT NOT NULL DEFAULT (datetime('now'))
            );

            -- Resource Planning: planned hours for one project, for one
            -- consultant, in one calendar month ('YYYY-MM'). Auto-filled
            -- (see resource_planning.build_plan) from a project's
            -- remaining estimated hours split across the next 3 months,
            -- defaulted onto whoever logged that project's most recent
            -- time entry — every cell here is then a saved, editable
            -- override of that default, exactly like pp_report_overrides
            -- overrides its own computed defaults.
            CREATE TABLE IF NOT EXISTS resource_plan (
                project_id INTEGER NOT NULL,
                redmine_user_id INTEGER NOT NULL,
                month TEXT NOT NULL,
                planned_hours REAL NOT NULL DEFAULT 0,
                updated_on TEXT NOT NULL DEFAULT (datetime('now')),
                PRIMARY KEY (project_id, redmine_user_id, month)
            );

            -- Reassigns a project to a specific consultant for Resource
            -- Planning, overriding the default "whoever logged the most
            -- recent time entry" guess (see resource_planning.build_plan).
            -- One project can only ever have one planned assignee at a
            -- time — reassigning replaces it outright, it does not split
            -- a project across two people.
            CREATE TABLE IF NOT EXISTS resource_plan_assignee (
                project_id INTEGER PRIMARY KEY,
                redmine_user_id INTEGER NOT NULL,
                redmine_user_name TEXT NOT NULL DEFAULT '',
                updated_on TEXT NOT NULL DEFAULT (datetime('now'))
            );

            -- An extra, manually-added planning row for a project that
            -- already has its normal (auto-detected or reassigned)
            -- consultant row — see resource_planning.build_plan and its
            -- "Split" button: splitting a project duplicates its row for
            -- a second consultant, with its own independently-editable
            -- planned hours in resource_plan, so the two rows' numbers
            -- can be manually rebalanced. Removing the split deletes the
            -- row here (and its resource_plan hour cells).
            CREATE TABLE IF NOT EXISTS resource_plan_extra_assignee (
                project_id INTEGER NOT NULL,
                redmine_user_id INTEGER NOT NULL,
                redmine_user_name TEXT NOT NULL DEFAULT '',
                updated_on TEXT NOT NULL DEFAULT (datetime('now')),
                PRIMARY KEY (project_id, redmine_user_id)
            );

            -- KSA projects aren't tracked in Redmine — their per-month
            -- figures (Total Revenue, Accumulated, Previous Accumulated,
            -- Amount to Take) are read from the monthly PP Report workbook's
            -- month tab via the upload on the PP Report Data admin screen
            -- (see pp_report.parse_ksa_workbook) and merged into that
            -- month's PP Report rows as read-only lines.
            CREATE TABLE IF NOT EXISTS ksa_import (
                month TEXT NOT NULL,
                excel_project_id INTEGER NOT NULL,
                project_code TEXT NOT NULL DEFAULT '',
                name TEXT NOT NULL DEFAULT '',
                status TEXT NOT NULL DEFAULT '',
                author TEXT NOT NULL DEFAULT '',
                est_hours REAL NOT NULL DEFAULT 0,
                spent_hours REAL NOT NULL DEFAULT 0,
                total_revenue REAL NOT NULL DEFAULT 0,
                accumulated REAL NOT NULL DEFAULT 0,
                previous_accumulated REAL NOT NULL DEFAULT 0,
                amount_to_take REAL NOT NULL DEFAULT 0,
                progress REAL,
                previous_amount_to_take REAL,
                updated_on TEXT NOT NULL DEFAULT (datetime('now')),
                PRIMARY KEY (month, excel_project_id)
            );

            -- KSA consultants' time entries, from the Intra timesheet
            -- export's KSA rows (see pp_report.parse_ksa_timesheet) — KSA
            -- projects aren't in Redmine, so there's no other source of
            -- their hours. Replaced per month on each upload.
            CREATE TABLE IF NOT EXISTS ksa_timesheet (
                month TEXT NOT NULL,
                spent_on TEXT NOT NULL,
                user_name TEXT NOT NULL,
                project_code TEXT NOT NULL DEFAULT '',
                description TEXT NOT NULL DEFAULT '',
                hours REAL NOT NULL DEFAULT 0
            );
            CREATE INDEX IF NOT EXISTS idx_ksa_timesheet_month ON ksa_timesheet (month);

            -- Stable app-only (negative) employee ids for KSA consultants
            -- who have no Redmine account, so their hourly rate (Employees
            -- screen) and utilization keep pointing at the same id across
            -- uploads even if the timesheet spells their name differently.
            CREATE TABLE IF NOT EXISTS ksa_person (
                name TEXT PRIMARY KEY,
                user_id INTEGER NOT NULL
            );
            """
        )
        _migrate(conn)
        _reinsert_migrated_data(conn, migrated)
        _seed_default_countries(conn)
